### ISSUE TITLE
Instance-ID is sometimes wrong.

### ISSUE THREAD

**Issue by titusz** [iscc/iscc-rs#4]
It seems the special case of an uneven number of chunks is not handled correctly. With uneven chunks the last chunk should be concatenated with itself. See https://github.com/iscc/iscc-specs/blob/master/src/iscc/iscc.py#L315

**Comment by Alexander-N** [comment]
Looking at https://github.com/iscc/iscc-rs/blob/f9f04f97e63/src/iid.rs#L51..L55 this is what I tried to do. How did you locate the error and do you have an example of the expected output?

**Comment by Alexander-N** [comment]
Closed by #5.
